name: Template List
on:
  - push

#### Needs to run as a cron ####
#  schedule:
#  - cron:  "*/60 * * * *"

jobs:
  template-list-make:
    name: update-list
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'crunchy-template-master'
    steps:
      - uses: actions/checkout@v2
      - uses: gva-ncarney/template-repository-usage-action@main  # v1.1.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          org: 'gva-ncarney'
          repo: 'crunchy-template-master'
